unit Unit11;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls;

type
  TForm11 = class(TForm)
    Button1: TButton;
    Button2: TButton;
    Button3: TButton;
    Button4: TButton;
    Button5: TButton;
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    Label4: TLabel;
    Label5: TLabel;
    Label6: TLabel;
    Label7: TLabel;
    Label8: TLabel;
    Label9: TLabel;
    Label10: TLabel;
    Label11: TLabel;
    Label12: TLabel;
    Label13: TLabel;
    Label14: TLabel;
    Label15: TLabel;
    Label16: TLabel;
    Label17: TLabel;
    Label18: TLabel;
    Label19: TLabel;
    Label20: TLabel;
    Label21: TLabel;
    Label22: TLabel;
    Label23: TLabel;
    Label24: TLabel;
    Label25: TLabel;
    Label26: TLabel;
    Label27: TLabel;
    Label28: TLabel;
    Label29: TLabel;
    Label30: TLabel;
    Label31: TLabel;
    Label32: TLabel;
    Label33: TLabel;
    Label34: TLabel;
    Label35: TLabel;
    Label36: TLabel;
    Label37: TLabel;
    Label38: TLabel;
    Label39: TLabel;
    Label40: TLabel;
    Label41: TLabel;
    Label42: TLabel;
    Label43: TLabel;
    Label44: TLabel;
    Label45: TLabel;
    Label46: TLabel;
    Label47: TLabel;
    Label48: TLabel;
    procedure Button1Click(Sender: TObject);
    procedure Button2Click(Sender: TObject);
    procedure Button3Click(Sender: TObject);
    procedure Button4Click(Sender: TObject);
    procedure Button5Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form11: TForm11;

implementation

{$R *.dfm}

procedure TForm11.Button1Click(Sender: TObject);
begin
label1.Caption:=  'ADD' ;
label2.Caption:=  'Суммирование без переноса Rd=Rd+Rr';
label3.Caption:=  'ADC' ;
label4.Caption:=  'суммирование с переносом Rd=Rd+Rr+C';
label5.Caption:=   'SUB'  ;
label6.Caption:=    'Вычитание без переноса Rd=Rd-Rr'   ;
label7.Caption:=   'SUBI' ;
label8.Caption:=    'Вычитание константы Rd=Rd-K8'   ;
label9.Caption:=   'SBC'  ;
label10.Caption:=  'Выситание с переносом Rd=Rd-Rr-C'   ;
label11.Caption:=    'SBCI' ;
label12.Caption:=   'Вычитание константы с переносом d=Rd-K8-C';
label13.Caption:=   'ADIW'  ;
label14.Caption:=   'Сложить константу и слово Rdh:Rdl=Rdh+Rdl+K6';
label15.Caption:=   'SBIW'   ;
label16.Caption:= 'Вычесть константу из слова Rdh:Rdl=Rdh:Rdl-K6';
label17.Caption:=    'MUL' ;
label18.Caption:=    'Умножение чисел без знака R1:R0=Rd*Rr';
label19.Caption:=  'MULS' ;
label20.Caption:=    'Умножение чисел со знаком R1:R0=Rd*Rr';
label21.Caption:=  'MULSU'   ;
label22.Caption:=  'Умножение числа со знаком с числом без знака R1:R0=Rd*Rr';
label23.Caption:=   'FMUL';
label24.Caption:=   'Умножение дробных чисел без знака R1:R0=(Rd*Rr)<<1' ;
label25.Caption:=   'FMULS'  ;
label26.Caption:=    'Умножение дробных чисел со знака R1:R0=(Rd*Rr)<<1' ;
label27.Caption:=  'FMULSU'  ;
label28.Caption:= 'Умножение дробного числа со знаком с числом без знака R1:R0=(Rd*Rr)<<1'  ;
label29.visible:=false ;
label30.visible:=false  ;
label31.visible:=false ;
label32.visible:=false ;
label33.visible:=false ;
label34.visible:=false  ;
label35.visible:=false ;
label36.visible:=false  ;
label37.visible:=false ;
label38.visible:=false  ;
label39.visible:=false ;
label40.visible:=false ;
label41.visible:=false ;
label42.visible:=false  ;
label43.visible:=false ;
label44.visible:=false  ;
label45.visible:=false ;
label46.visible:=false  ;
label47.visible:=false ;
label48.visible:= false ;

end;

procedure TForm11.Button2Click(Sender: TObject);
begin
label1.Caption:=  'AND' ;
label2.Caption:=  'Логическое И Rd=Rd*Rr';
label3.Caption:=  'ANDI' ;
label4.Caption:=  'Логическое И с константой Rd=Rd*K8';
label5.Caption:=   'OR'  ;
label6.Caption:=    'Логическое ИЛИ  Rd=Rd V Rr'   ;
label7.Caption:=   'ORI' ;
label8.Caption:=    'Логическое ИЛИ с константой Rd=Rd V K8'   ;
label9.Caption:=   'EOR'  ;
label10.Caption:=  'Логическое исключающее ИЛИ Rd=Rd EOR Rr'   ;
label11.Caption:=    'COM' ;
label12.Caption:=   'Побитная инверсия Rd=$FF-Rd';
label13.Caption:=   'NEG'  ;
label14.Caption:=   'Изменение знака (доп. код) Rd=$00-Rd';
label15.Caption:=   'SBR'   ;
label16.Caption:= 'Установить бит (биты) врегистре Rd=Rd V K8';
label17.Caption:=  'INC' ;
label18.Caption:=    'Инкрементировать значение регистра Rd=Rd+1';
label19.Caption:=  'DEC ' ;
label20.Caption:='Декрементировать значение регистра Rd=Rd1';
label21.Caption:=  'TST'   ;
label22.Caption:= 'Проверка на ноль либо отрицательность Rd=Rd*Rd';
label23.Caption:=   'CLR';
label24.Caption:=   'Очистить регистр Rd = 0' ;
label25.Caption:=   'SER'  ;
label26.Caption:=    'Установить регистр Rd=$FF' ;
label27.visible:=false ;
label28.visible:=false  ;
label29.visible:=false ;
label30.visible:=false  ;
label31.visible:=false ;
label32.visible:=false  ;
label33.visible:=false ;
label34.visible:=false  ;
label35.visible:=false ;
label36.visible:=false  ;
label37.visible:=false ;
label38.visible:=false  ;
label39.visible:=false ;
label40.visible:=false  ;
label41.visible:=false ;
label42.visible:=false  ;
label43.visible:=false ;
label44.visible:=false  ;
label45.visible:=false ;
label46.visible:=false  ;
label47.visible:=false ;
label48.visible:=false  ;
end;

procedure TForm11.Button3Click(Sender: TObject);
begin
label27.visible:=true ;
label28.visible:=true  ;
label29.visible:=true ;
label30.visible:=true  ;
label31.visible:=true ;
label32.visible:=true ;
label33.visible:=true ;
label34.visible:=true  ;
label35.visible:=true ;
label36.visible:=true  ;
label37.visible:=true ;
label38.visible:=true  ;
label39.visible:=true ;
label40.visible:=true  ;
label41.visible:=true ;
label42.visible:=true  ;
label43.visible:=true ;
label44.visible:=true  ;
label45.visible:=true ;
label46.visible:=true  ;
label47.visible:=true ;
label48.visible:= true ;
label1.Caption:='RJMP' ;
label2.Caption:='Относительный переход PC=PC+k+1';
label3.Caption:='IJMP' ;
label4.Caption:='Косвенный переход на (Z) PC = Z';
label5.Caption:='EIJMP'  ;
label6.Caption:='Расширенный косвенныйпереход на (Z)  STACK=PC+1, PC(15:0)=Z, PC(21:16)=EIND'  ;
label7.Caption:='JMP' ;
label8.Caption:='Переход PC=k'   ;
label9.Caption:='RCALL'  ;
label10.Caption:='Относительный вызов подпрограммы STACK=PC+1, PC=PC+k+1'   ;
label11.Caption:='ICALL' ;
label12.Caption:='Косвенный вызов (Z) STACK=PC+1, PC=Z';
label13.Caption:='EICALL'  ;
label14.Caption:='Расширенный косвенныйвызов (Z)STACK=PC+1, PC(15:0)=Z, PC(21:16)=EIND';
label15.Caption:='CALL'   ;
label16.Caption:='Вызов подпрограммы STACK=PC+2, PC=k';
label17.Caption:='RET' ;
label18.Caption:='Возврат из подпрограммы PC=STACK';
label19.Caption:='RETI' ;
label20.Caption:='Возврат из прерывания PC=STACK';
label21.Caption:='CPSE'   ;
label22.Caption:='Сравнить, пропустить, если равны if (Rd ==Rr) PC=PC 2or 3';
label23.Caption:='CP';
label24.Caption:='Сравнить Rd -Rr' ;
label25.Caption:='CPC'  ;
label26.Caption:='Сравнить с переносом Rd - Rr - C' ;
label27.Caption:='CPI' ;
label28.Caption:='Сравнить с константой Rd - K' ;
label29.Caption:='SBRC' ;
label30.Caption:='Пропустить, если бит в регистре очищен if(Rr(b)==0) PC=PC+2or3' ;
label31.Caption:='SBIC' ;
label32.Caption:='Пропустить, если бит в порту очищен if(I/O(P,b)==0) PC=PC+2or3' ;
label33.Caption:='BRBC' ;
label34.Caption:='Перейти, если флаг в SREG очищен if(SREG(s)==0) PC = PC+k+1' ;
label35.Caption:='BREQ' ;
label36.Caption:='Перейти, если равно if(Z==1) PC=PC+k+1' ;
label37.Caption:='BRNE' ;
label38.Caption:='Перейти, если не равно if(Z==0) PC=PC+k+1' ;
label39.Caption:='BRCS' ;
label40.Caption:='Перейти, если перенос установлен if(C==1) PC=PC+k+1' ;
label41.Caption:='BRLO' ;
label42.Caption:='Перейти, если меньше if(C==1) PC=PC+k+1' ;
label43.Caption:='BRMI' ;
label44.Caption:='Перейти, если минус if(N==1) PC = PC + k + 1' ;
label45.Caption:='BRPL' ;
label46.Caption:='Перейти, если плюс if(N==0) PC=PC+k+1' ;
label47.Caption:='BRVC' ;
label48.Caption:='Перейти, если флаг переполнения очищен if(V==0) PC=PC+k+1' ;

end;

procedure TForm11.Button4Click(Sender: TObject);
begin
label27.visible:=true ;
label28.visible:=true  ;
label29.visible:=true ;
label30.visible:=true  ;
label31.visible:=true ;
label32.visible:=true ;
label33.visible:=true ;
label34.visible:=true  ;
label35.visible:=true ;
label36.visible:=true  ;
label37.visible:=true ;
label38.visible:=true  ;
label39.visible:=true ;
label40.visible:=true  ;
label41.visible:=true ;
label42.visible:=true  ;
label43.visible:=true ;
label44.visible:=true  ;
label45.visible:=true ;
label46.visible:=true  ;
label47.visible:=true ;
label48.visible:= true ;
label1.Caption:='MOV' ;
label2.Caption:='Скопировать регистр Rd = Rr';
label3.Caption:='MOVW' ;
label4.Caption:='Скопировать пару регистров Rd+1:Rd=Rr+1:Rr, r,d - четн';
label5.Caption:='LDI'  ;
label6.Caption:='Загрузить константу Rd = K8'  ;
label7.Caption:='LDS' ;
label8.Caption:='Прямая загрузка Rd = (k)'   ;
label9.Caption:='LD'  ;
label10.Caption:='Косвенная загрузка Rd = (X)'   ;
label11.Caption:='LD' ;
label12.Caption:='Косвенная загрузка с постинкрементом Rd = (X), X=X+1';
label13.Caption:='LD'  ;
label14.Caption:='Косвенная загрузка с предекрементом X=X-1, Rd = (X)';
label15.Caption:='LD'   ;
label16.Caption:='Косвенная загрузка Rd = (Y)';
label17.Caption:='LD' ;
label18.Caption:='Косвенная загрузка с постинкрементом Rd = (Y), Y=Y+1';
label19.Caption:='LD' ;
label20.Caption:='Косвенная загрузка с предекрементом Y=Y-1, Rd = (Y)';
label21.Caption:='LDD'   ;
label22.Caption:='Косвенная загрузка с замещением Rd = (Y+q)';
label23.Caption:='LDD';
label24.Caption:='Косвенная загрузка с замещением Rd = (Z+q)' ;
label25.Caption:='STS'  ;
label26.Caption:='Прямое сохранение (k) = Rr' ;
label27.Caption:='ST' ;
label28.Caption:='Косвенное сохранение (X) = Rr' ;
label29.Caption:='LPM' ;
label30.Caption:='Загрузка из программной памяти R0 = (Z)' ;
label31.Caption:='ELPM' ;
label32.Caption:='Расширенная загрузка из программной памяти R0 = (RAMPZ:Z)' ;
label33.Caption:='LPM' ;
label34.Caption:='Загрузка из программной памяти с постинкрементом Rd = (Z), Z=Z+1' ;
label35.Caption:='ELPM' ;
label36.Caption:='Расширенная загрузка из программной памяти с постинкрементом Rd = (RAMPZ:Z), Z= Z+1' ;
label37.Caption:='SPM' ;
label38.Caption:='Сохранение в программной памяти (Z) = R1:R0' ;
label39.Caption:='ESPM' ;
label40.Caption:='Расширенное сохранение в программной памяти (RAMPZ:Z)=R1:R0' ;
label41.Caption:='IN' ;
label42.Caption:='Чтение порта Rd = P' ;
label43.Caption:='OUT' ;
label44.Caption:='Запись в порт P = Rr' ;
label45.Caption:='PUSH' ;
label46.Caption:='Занесение регистра в стек STACK = Rr' ;
label47.Caption:='POP' ;
label48.Caption:='Извлечение регистра из стека Rd = STACK' ;
end;

procedure TForm11.Button5Click(Sender: TObject);
begin
label27.visible:=true ;
label28.visible:=true  ;
label29.visible:=true ;
label30.visible:=true  ;
label31.visible:=true ;
label32.visible:=true ;
label33.visible:=true ;
label34.visible:=true  ;
label35.visible:=true ;
label36.visible:=true  ;
label37.visible:=true ;
label38.visible:=true  ;
label39.visible:=true ;
label40.visible:=true  ;
label41.visible:=true ;
label42.visible:=true  ;
label43.visible:=true ;
label44.visible:=true  ;
label45.visible:=true ;
label46.visible:=true  ;
label47.visible:=true ;
label48.visible:= true ;
label1.Caption:='LSL' ;
label2.Caption:='Логический сдвиг влево Rd(n+1)=Rd(n),Rd(0)=0, C=Rd(7)';
label3.Caption:='LSR' ;
label4.Caption:='Логический сдвиг вправо Rd(n)=Rd(n+1),Rd(7)=0, C=Rd(0)';
label5.Caption:='ROL'  ;
label6.Caption:='Циклический сдвиг влево через флаг переноса C Rd(0)=C,Rd(n+1)=Rd(n),C=Rd(7)'  ;
label7.Caption:='ROR' ;
label8.Caption:='Циклический сдвиг вправо через C Rd(7)=C, Rd(n)=Rd(n+1), C=Rd(0)'   ;
label9.Caption:='ASR'  ;
label10.Caption:='Арифметический сдвиг вправо Rd(n)=Rd(n+1),n=0,...,6'   ;
label11.Caption:='SWAP' ;
label12.Caption:='Перестановка половин байта Rd(3...0) = Rd(7...4),Rd(7...4) = Rd(3...0)';
label13.Caption:='BSET'  ;
label14.Caption:='Установка флага SREG(s) = 1';
label15.Caption:='BCLR'   ;
label16.Caption:='Очистка флага SREG(s) = 0';
label17.Caption:='SBI' ;
label18.Caption:='Установить бит в порту I/O(P,b) = 1';
label19.Caption:='CBI' ;
label20.Caption:='Очистить бит в порту I/O(P,b) = 0';
label21.Caption:='BST'   ;
label22.Caption:='Сохранить бит из регистра в T T = Rr(b)';
label23.Caption:='BLD';
label24.Caption:='Загрузить бит из T в регистр Rd(b) = T' ;
label25.Caption:='SEC'  ;
label26.Caption:='Установить флаг переноса C =1' ;
label27.Caption:='CLC' ;
label28.Caption:='Очистить флаг прерываний I = 0' ;
label29.Caption:='SES' ;
label30.Caption:='Установить флаг числа со знаком S = 1' ;
label31.Caption:='CLN' ;
label32.Caption:='Очистить флаг числа со знаком S = 0' ;
label33.Caption:='SEV' ;
label34.Caption:='Установить флаг переполнения V = 1' ;
label35.Caption:='CLV' ;
label36.Caption:='Очистить флаг переполнения V = 0' ;
label37.Caption:='SET' ;
label38.Caption:='Установить флаг T T = 1' ;
label39.Caption:='CLT' ;
label40.Caption:='Очистить флаг T T = 0' ;
label41.Caption:='SEH' ;
label42.Caption:='Установить флаг внутреннего переноса H = 1' ;
label43.Caption:='CLH' ;
label44.Caption:='Очистить флаг внутреннего переноса H = 0' ;
label45.Caption:='NOP' ;
label46.Caption:='Нет операции' ;
label47.Caption:='SLEEP' ;
label48.Caption:='Спать (уменьшить энергопотребление)' ;
end;

end.
